# Generated by Django 5.1.1 on 2024-09-26 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mechTest', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Owner',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
