# Generated by Django 5.1.1 on 2024-09-26 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechTest', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('owner_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
