# Generated by Django 5.1.1 on 2024-09-26 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechTest', '0004_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_image', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
