# Generated by Django 5.1.1 on 2024-09-26 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechTest', '0005_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_email', models.EmailField(max_length=254)),
                ('description', models.TextField()),
                ('status', models.IntegerField()),
            ],
        ),
    ]
